# Generated by Django 3.1.2 on 2020-10-28 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0002_figure_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure_details',
            name='aspect',
        ),
        migrations.RemoveField(
            model_name='figure_details',
            name='description',
        ),
        migrations.RemoveField(
            model_name='figure_details',
            name='figid',
        ),
        migrations.RemoveField(
            model_name='figure_details',
            name='is_caption',
        ),
        migrations.RemoveField(
            model_name='figure_details',
            name='is_multiple',
        ),
        migrations.RemoveField(
            model_name='figure_details',
            name='object',
        ),
        migrations.RemoveField(
            model_name='figure_details',
            name='origreftext',
        ),
        migrations.RemoveField(
            model_name='figure_details',
            name='subfig',
        ),
        migrations.AddField(
            model_name='figure_details',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='figure_details',
            name='imgPath',
            field=models.CharField(default='', max_length=300),
        ),
    ]
